### ISSUE TITLE
Pseudo-variables does not work.

### ISSUE THREAD

**Issue by albertone** [vmoulin78/codeigniter-layout-library#3]
Hi,

Pseudo variables like {elapsed_time} does not work. I test the library with de default view file welcome.php and {elapsed_time} does not print the value. It shows like "Page rendered in {elapsed_time} seconds. CodeIgniter Version 3.1.5".

**Comment by vmoulin78** [comment]
Hi,
There is no preprocessor that converts pseudo variables into PHP code.
You have to write PHP code directly.
