### ISSUE TITLE
How to pass $data to blocks or inner templates?

### ISSUE THREAD

**Issue by albertone** [vmoulin78/codeigniter-layout-library#5]
Hi,

I have testing the library and I would like to use include_template() or block() functions inside a template for generate dynamic content like menus but it does not possible pass data to the blocks or templates included.

Actually I do that with _load_view()_ and _trigger_content_section()_ as you describes on readme.

For example, if we have a template which have a header with dynamic menu, what is the way to implement it using the template?

**Comment by vmoulin78** [comment]
Hello Albertone,

In fact, what you've done is just the right way of doing what you want.
The template system with the _include_template()_ and _block()_ methods are for static code.

If your menu is built dynamically, you have to create a view (or many views if necessary) for the menu and then, use the _load_view()_ and _trigger_content_section()_ methods.

So, you can't pass data to a template or a block but the $CI variable is available
If you have a session data _user_profile_, you can access it with:
`$CI->session->user_profile`

Vince

**Comment by albertone** [comment]
Hello @vmoulin78 

Thanks for you answer. So we can close this issue.

Thank you for your attention.
Alberto
